[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.5"

[[constraint]]
  name = "github.com/JaSei/pathutil-go"
  branch = "implementation"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "1.12.0"

[[constraint]]
  name = "github.com/nishanths/license"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.0.1"
